
services:

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - "./svc/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    networks:
      antena:
        ipv4_address: "172.0.33.2"
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      antena:
        ipv4_address: "172.0.33.3"
    ports:
      - "80:80"
    volumes:
      - "./static:/usr/share/nginx/html:ro"
      - "./svc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - mqtt
    restart: unless-stopped

  n1:
    container_name: n1
    build:
      context: ./svc/udp
      dockerfile: Dockerfile
    environment:
      - MQTT_HOST=172.0.33.2
      - MQTT_PORT=1883
    networks:
      antena:
        ipv4_address: "172.0.33.4"
    ports:
      - "12060:12060/udp"
    volumes:
      - "./cfg:/app/cfg"
    depends_on:
      - mqtt
    restart: unless-stopped

  control:
    container_name: control
    build:
      context: ./svc/control
      dockerfile: Dockerfile
    environment:
      - MQTT_HOST=172.0.33.2
      - MQTT_PORT=1883
    networks:
      antena:
        ipv4_address: "172.0.33.5"
    volumes:
      - "./cfg:/app/cfg"
    depends_on:
      - mqtt
    restart: unless-stopped

networks:
    antena:
        driver: bridge
        ipam:
            config:
                - subnet: 172.0.33.0/24
