services:

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - "./svc/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    networks:
      antena:
        ipv4_address: "172.0.33.2"
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      antena:
        ipv4_address: "172.0.33.3"
    ports:
      - "80:80"
    volumes:
      - "./static:/usr/share/nginx/html:ro"
      - "./svc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - mqtt
    restart: unless-stopped

  flex-stn1:
    container_name: flex-stn1
    build:
      context: ./svc/flex-mqtt
      dockerfile: Dockerfile
    networks:
      antena:
        ipv4_address: "172.0.33.4"
    ports:
      - "5051:5051/udp"
    environment:
      UDPPORT: "5051"
      FLEXIP: "192.168.88.51"
      FLEXPORT: "4992"
      STN: "stn1"
      MQTT_HOST: "mqtt"
      MQTT_PORT: "1883"
    depends_on:
      - mqtt
    restart: unless-stopped

  flex-stn2:
    container_name: flex-stn2
    build:
      context: ./svc/flex-mqtt
      dockerfile: Dockerfile
    networks:
      antena:
        ipv4_address: "172.0.33.6"
    ports:
      - "5052:5052/udp"
    environment:
      UDPPORT: "5052"
      FLEXIP: "192.168.88.52"
      FLEXPORT: "4992"
      STN: "stn2"
      MQTT_HOST: "mqtt"
      MQTT_PORT: "1883"
    depends_on:
      - mqtt
    restart: unless-stopped

  control:
    container_name: control
    build:
      context: ./svc/control
      dockerfile: Dockerfile
    networks:
      antena:
        ipv4_address: "172.0.33.5"
    volumes:
      - "./cfg:/app/cfg"
    depends_on:
      - mqtt
    restart: unless-stopped

networks:
    antena:
        driver: bridge
        ipam:
            config:
                - subnet: 172.0.33.0/24
